-- Harden users table access and record admin changes.
-- 1. users update is admin only
-- 2. users select is limited for non-admins
-- 3. admin audit logs are stored in a dedicated table
-- 4. admin detection uses a SECURITY DEFINER helper to avoid users-table RLS recursion

create or replace function public.current_user_is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.users
    where id = auth.uid()
      and role = 'admin'
      and is_active = true
  );
$$;

alter table public.users enable row level security;

create table if not exists public.user_admin_audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid not null references public.users(id),
  target_user_id uuid not null references public.users(id),
  action text not null check (action in ('user_created', 'role_changed', 'active_changed')),
  old_role text null check (old_role in ('admin', 'member')),
  new_role text null check (new_role in ('admin', 'member')),
  old_is_active boolean null,
  new_is_active boolean null,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.user_admin_audit_logs enable row level security;

drop policy if exists users_select on public.users;
drop policy if exists users_update on public.users;
drop policy if exists users_update_admin_manage on public.users;
drop policy if exists user_admin_audit_logs_select_admin on public.user_admin_audit_logs;
drop policy if exists user_admin_audit_logs_insert_admin on public.user_admin_audit_logs;

create policy users_select
  on public.users
  for select
  to authenticated
  using (
    public.current_user_is_admin()
    or id = auth.uid()
    or is_active = true
  );

create policy users_update_admin_manage
  on public.users
  for update
  to authenticated
  using (public.current_user_is_admin())
  with check (public.current_user_is_admin());

create policy user_admin_audit_logs_select_admin
  on public.user_admin_audit_logs
  for select
  to authenticated
  using (public.current_user_is_admin());

create policy user_admin_audit_logs_insert_admin
  on public.user_admin_audit_logs
  for insert
  to authenticated
  with check (
    public.current_user_is_admin()
    and actor_user_id = auth.uid()
  );
