-- Harden users table access and record admin changes.
-- 1. users update is admin only
-- 2. users select is limited for non-admins
-- 3. admin audit logs are stored in a dedicated table

alter table public.users enable row level security;

create table if not exists public.user_admin_audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid not null references public.users(id),
  target_user_id uuid not null references public.users(id),
  action text not null check (action in ('user_created', 'role_changed', 'active_changed')),
  old_role text null check (old_role in ('admin', 'member')),
  new_role text null check (new_role in ('admin', 'member')),
  old_is_active boolean null,
  new_is_active boolean null,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.user_admin_audit_logs enable row level security;

drop policy if exists users_select on public.users;
drop policy if exists users_update on public.users;
drop policy if exists users_update_admin_manage on public.users;
drop policy if exists user_admin_audit_logs_select_admin on public.user_admin_audit_logs;
drop policy if exists user_admin_audit_logs_insert_admin on public.user_admin_audit_logs;

create policy users_select
  on public.users
  for select
  to authenticated
  using (
    (
      select users_1.role
      from public.users as users_1
      where users_1.id = auth.uid()
    ) = 'admin'
    or id = auth.uid()
    or is_active = true
  );

create policy users_update_admin_manage
  on public.users
  for update
  to authenticated
  using (
    (
      select users.role
      from public.users
      where users.id = auth.uid()
    ) = 'admin'
  )
  with check (
    (
      select users.role
      from public.users
      where users.id = auth.uid()
    ) = 'admin'
  );

create policy user_admin_audit_logs_select_admin
  on public.user_admin_audit_logs
  for select
  to authenticated
  using (
    (
      select users.role
      from public.users
      where users.id = auth.uid()
    ) = 'admin'
  );

create policy user_admin_audit_logs_insert_admin
  on public.user_admin_audit_logs
  for insert
  to authenticated
  with check (
    (
      select users.role
      from public.users
      where users.id = auth.uid()
    ) = 'admin'
    and actor_user_id = auth.uid()
  );
